/**
 * @file port_console_uart.c
 * @brief Console UART (USART1) interface implementation
 *
 * Independent of port_uart.c (USART3, the protocol port); this file is
 * dedicated to log output on USART1.
 *
 * Design notes:
 *   - console_uart only needs TX (for log output), no RX interrupt
 *   - init/deinit/write all use huart1 (the CubeMX-generated USART1 handle)
 *   - read / register_rx_cb provide empty stubs (the interface requires them)
 *
 * Why not merge with port_uart.c:
 *   - The protocol port needs an RX interrupt callback mechanism (to receive host commands)
 *   - The log port only needs TX (blocking output)
 *   - Keeping them separate gives clear responsibilities and no interference
 */

#include "../hal_if_defines.h"
#include "port.h"
#include "main.h"

extern UART_HandleTypeDef huart1;   /* Generated by CubeMX in usart.c */

static int console_uart_init(uint32_t baudrate)
{
    (void)baudrate;
    /* UART is already initialized by main.c -> MX_USART1_UART_Init(); nothing to do here */
    return 0;
}

static void console_uart_deinit(void)
{
    /* No cleanup; the log port stays available all the time */
}

/**
 * Blocking log output.
 * HAL_MAX_DELAY would block forever on a UART error; the bootloader runs only
 * briefly, so this is acceptable. If you are worried about stalls, change
 * timeout to 100 (100ms).
 */
static int console_uart_write(const uint8_t *data, uint32_t size)
{
    HAL_UART_Transmit(&huart1, (uint8_t *)data, size, 100);
    return (int)size;
}

/* Log port does not need RX; empty stub */
static int console_uart_read(uint8_t *data, uint32_t size, uint32_t timeout_ms)
{
    (void)data;
    (void)size;
    (void)timeout_ms;
    return 0;
}

static void console_uart_register_rx_cb(void (*callback)(const uint8_t *data, uint32_t size))
{
    (void)callback;
    /* Log port does not support RX callback */
}

const uart_if_t console_uart_stm32f4 = {
    .init              = console_uart_init,
    .deinit            = console_uart_deinit,
    .write             = console_uart_write,
    .read              = console_uart_read,
    .register_rx_cb    = console_uart_register_rx_cb,
    .instance          = 1,   /* USART1 */
};
