#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
generate_keys.py - Generate an ECDSA P-256 key pair

Usage:
  python generate_keys.py
  python generate_keys.py --outdir ./keys    # specify output directory
"""

import os
import sys
import argparse

# Windows console UTF-8 support (prevents crashes when printing emoji)
if sys.platform == 'win32':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except Exception:
        pass

try:
    from ecdsa import SigningKey, NIST256p
except ImportError:
    print("❌ Missing the ecdsa library. Install it with: pip install ecdsa")
    sys.exit(1)


def generate_keypair(outdir="."):
    """Generate an ECDSA P-256 key pair"""

    # Generate private key
    sk = SigningKey.generate(curve=NIST256p)
    vk = sk.get_verifying_key()

    # Raw public-key bytes (64 bytes: x[32] || y[32])
    pubkey_bytes = vk.to_string()
    assert len(pubkey_bytes) == 64, f"Unexpected public key length: {len(pubkey_bytes)}"

    # ===== 1. Save the private key =====
    priv_path = os.path.join(outdir, "private_key.pem")
    with open(priv_path, "wb") as f:
        f.write(sk.to_pem())
    print(f"✅ Private key saved: {priv_path}")
    print(f"   ⚠️ Keep it secret! Do NOT share it with customers and do NOT commit it to Git!")

    # ===== 2. Generate the public-key C header file =====
    hdr_path = os.path.join(outdir, "ecdsa_pubkey.h")
    with open(hdr_path, "w", encoding='utf-8') as f:
        f.write("/**\n")
        f.write(" * @file ecdsa_pubkey.h\n")
        f.write(" * @brief ECDSA P-256 public key (auto-generated by generate_keys.py)\n")
        f.write(" *\n")
        f.write(" * ⚠️ Changing the private key means you MUST also update this file and recompile the bootloader.\n")
        f.write(" */\n\n")
        f.write("#ifndef ECDSA_PUBKEY_H\n")
        f.write("#define ECDSA_PUBKEY_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("static const uint8_t ecdsa_public_key[64] = {\n")

        # x coordinate (32 bytes, 2 rows of 16)
        f.write("    /* x coordinate */\n")
        for i in range(0, 32, 16):
            line = ", ".join(f"0x{b:02X}" for b in pubkey_bytes[i:i + 16])
            f.write(f"    {line},\n")

        # y coordinate (32 bytes, 2 rows of 16)
        f.write("    /* y coordinate */\n")
        for i in range(32, 64, 16):
            line = ", ".join(f"0x{b:02X}" for b in pubkey_bytes[i:i + 16])
            f.write(f"    {line},\n")

        f.write("};\n\n")
        f.write("#endif /* ECDSA_PUBKEY_H */\n")

    print(f"✅ Public key saved: {hdr_path}")
    print(f"   Copy it to Middlewares/bootloader/core/ecdsa_pubkey.h, replacing the placeholder values")

    # ===== 3. Print the public-key fingerprint (for verification) =====
    import hashlib
    fingerprint = hashlib.sha256(pubkey_bytes).hexdigest()[:16].upper()
    print(f"\n📋 Public key fingerprint: {fingerprint}")
    print(f"   (After compiling, you can compare it against the MCU boot log)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate an ECDSA P-256 key pair")
    parser.add_argument("--outdir", default=".", help="Output directory (default: current directory)")
    args = parser.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    generate_keypair(args.outdir)
